### PR TITLE
Fix tool agent

### LINKED ISSUE #41: Fix agent
Tool execution is a mess, need some refactoring

### PR DESCRIPTION
**Pull request by valentimarco**
Closes #41

### CODE REVIEW

File: src/looking_glass/agent-manager.ts [hunk 1]
```diff
@@ -27,7 +27,7 @@ import { MAIN_PROMPT_PREFIX, MAIN_PROMPT_SUFFIX, TOOL_PROMPT } from './prompts.t
 export class AgentManager {
 	private verboseRunnable = new RunnableLambda({
 		func: (x: any) => {
-			if (parsedEnv.verbose) log.dir(x)
+			if (parsedEnv.verbose) log.dir(x?.toString())
```
Comment (zAlweNy26) [inline src/looking_glass/agent-manager.ts:28]: Why you need to do this? `log.dir` already outputs the entire variable passed, no matter what type it is.

File: src/looking_glass/cheshire-cat.ts [hunk 2]
```diff
@@ -187,10 +193,9 @@ export class CheshireCat {
 			{ logMessage: 'Failed to retrieve embedder size. Reset to FakeEmbeddings.' },
 		)
 
+		// QUESTION: Should we also set it in the db?
 		if (error) {
-			// QUESTION: Should we also set it in the db?
 			this.embedder = (await getEmbedder('FakeEmbeddings'))!.initModel({})
-			await this.loadMemory()
```
Comment (zAlweNy26) [inline src/looking_glass/cheshire-cat.ts:193]: Are you sure about removing this? I did this to set the embedderSize property

File: src/routes/embedder.ts [hunk 3]
```diff
@@ -55,6 +55,13 @@ export const embedderRoutes = new Elysia({
 	if (!emb) throw HttpError.NotFound(`The passed embedder id '${id}' doesn't exist in the list of available embedders.`)
 	const parsed = emb.config.safeParse(body)
 	if (!parsed.success) throw HttpError.InternalServer(parsed.error.errors.map(e => e.message).join())
+	db.update((db) => {
+		db.selectedEmbedder = id
+		const embIndex = db.embedders.findIndex(l => l.name === id)
+		if (embIndex === -1) db.embedders.push({ name: id, value: parsed.data })
+		else db.embedders[embIndex]!.value = parsed.data
+	})
```
Comment (zAlweNy26) [inline src/routes/embedder.ts:64]: This needs to be discussed, because it can mess things up if the embedder setup throws an error. (Discuss the same for LLM configs)

**Comment by zAlweNy26** [comment]
Please always run `bun run lint:fix` before committing.

File: src/looking_glass/cheshire-cat.ts (hunk 2 above)
Comment (valentimarco) [reply src/looking_glass/cheshire-cat.ts:193]: ops my error

File: src/looking_glass/agent-manager.ts (hunk 1 above)
Comment (valentimarco) [reply src/looking_glass/agent-manager.ts:28]: bc i want the prompt that will be used by the model.

**Review by typegaro — APPROVED** [review]

File: src/looking_glass/agent-manager.ts (hunk 1 above)
Comment (valentimarco) [reply src/looking_glass/agent-manager.ts:28]: If i don't put the method `toString()`
```ts
ccat_ts_dev                | ChatPromptValue {
ccat_ts_dev                |   lc_serializable: true,
ccat_ts_dev                |   lc_kwargs: {
ccat_ts_dev                |     messages: [
ccat_ts_dev                |       SystemMessage {
ccat_ts_dev                |   "content": "Create a JSON with the correct \"action\" and \"actionInput\" to help the Human.\nYou can use one of these actions:\n - \"get-time\": Useful to get the current time when asked. Input is always null.\n  - \"no_action\": Use this action if no relevant action is available. Input is always null.\n\nThe JSON must have the following structure:\n```json\n{\n\t\"action\": // string - represents the name of the action to take, should be one of [\"get-time\", \"no_action\"]\n\t\"actionInput\": // string or null - represents the input to the action\n}\n```\t\n\n## Below some examples to better understand your task\n\n\n\nQuestion: Get the time\n{\n\t\"action\": \"get-time\",\n\t\"actionInput\": // Input of the action according to its description\n}\n\n\nWhen you think there isn't any action that can help the Human, choose \"no_action\" and mantain the JSON structure described before.",
ccat_ts_dev                |   "additional_kwargs": {},
ccat_ts_dev                |   "response_metadata": {}
ccat_ts_dev                | }, HumanMessage {
ccat_ts_dev                |   "content": "what time is it",
ccat_ts_dev                |   "name": "user",
ccat_ts_dev                |   "additional_kwargs": {},
ccat_ts_dev                |   "response_metadata": {}
ccat_ts_dev                | }
ccat_ts_dev                |     ],
ccat_ts_dev                |   },
ccat_ts_dev                |   lc_namespace: [ "langchain_core", "prompt_values" ],
ccat_ts_dev                |   messages: [
ccat_ts_dev                |     SystemMessage {
ccat_ts_dev                |   "content": "Create a JSON with the correct \"action\" and \"actionInput\" to help the Human.\nYou can use one of these actions:\n - \"get-time\": Useful to get the current time when asked. Input is always null.\n  - \"no_action\": Use this action if no relevant action is available. Input is always null.\n\nThe JSON must have the following structure:\n```json\n{\n\t\"action\": // string - represents the name of the action to take, should be one of [\"get-time\", \"no_action\"]\n\t\"actionInput\": // string or null - represents the input to the action\n}\n```\t\n\n## Below some examples to better understand your task\n\n\n\nQuestion: Get the time\n{\n\t\"action\": \"get-time\",\n\t\"actionInput\": // Input of the action according to its description\n}\n\n\nWhen you think there isn't any action that can help the Human, choose \"no_action\" and mantain the JSON structure described before.",
ccat_ts_dev                |   "additional_kwargs": {},
ccat_ts_dev                |   "response_metadata": {}
ccat_ts_dev                | }, HumanMessage {
ccat_ts_dev                |   "content": "what time is it",
ccat_ts_dev                |   "name": "user",
ccat_ts_dev                |   "additional_kwargs": {},
ccat_ts_dev                |   "response_metadata": {}
ccat_ts_dev                | }
ccat_ts_dev                |   ],
ccat_ts_dev                |   toString: [Function: toString],
ccat_ts_dev                |   toChatMessages: [Function: toChatMessages],
ccat_ts_dev                |   lc_id: [Getter],
ccat_ts_dev                |   lc_secrets: [Getter],
ccat_ts_dev                |   lc_attributes: [Getter],
ccat_ts_dev                |   lc_aliases: [Getter],
ccat_ts_dev                |   lc_serializable_keys: [Getter],
ccat_ts_dev                |   toJSON: [Function: toJSON],
ccat_ts_dev                |   toJSONNotImplemented: [Function: toJSONNotImplemented],
ccat_ts_dev                | }
```

Comment (zAlweNy26) [reply src/looking_glass/agent-manager.ts:28]: And if you put it? What's the output? If you are sure the variable passed is always serializable through the .toString method, for me it's ok.

Comment (valentimarco) [reply src/looking_glass/agent-manager.ts:28]:
```
ccat_ts_dev                | System: Create a JSON with the correct "action" and "actionInput" to help the Human.
ccat_ts_dev                | You can use one of these actions:
ccat_ts_dev                |  - "get-time": Useful to get the current time when asked. Input is always null.
ccat_ts_dev                |   - "no_action": Use this action if no relevant action is available. Input is always null.
ccat_ts_dev                | 
ccat_ts_dev                | The JSON must have the following structure:
ccat_ts_dev                | ```json
ccat_ts_dev                | {
ccat_ts_dev                |    "action": // string - represents the name of the action to take, should be one of ["get-time", "no_action"]
ccat_ts_dev                |    "actionInput": // string or null - represents the input to the action
ccat_ts_dev                | }
ccat_ts_dev                | ```
ccat_ts_dev                | 
ccat_ts_dev                | ## Below some examples to better understand your task
ccat_ts_dev                | 
ccat_ts_dev                | 
ccat_ts_dev                | 
ccat_ts_dev                | Question: What time is it
ccat_ts_dev                | {
ccat_ts_dev                |    "action": "get-time",
ccat_ts_dev                |    "actionInput": // Input of the action according to its description
ccat_ts_dev                | }
ccat_ts_dev                | 
ccat_ts_dev                | 
ccat_ts_dev                | When you think there isn't any action that can help the Human, choose "no_action" and mantain the JSON structure described before.
```
For all langchain runnables is implemented
